### PR TITLE
Mention bootcamp

### PR DESCRIPTION
**Pull request by iHiD**
Not sure if I need the double `\n` to have a proper linebreak? 

Feel free to tweak to whatever is good!

### CODE REVIEW

**Comment by IsaacG** [comment]
Do we want to completely drop all other suggestions? Or maybe keep them in a shorter form?

**Comment by IsaacG** [comment]
See !109

**Comment by iHiD** [comment]
I'd personally drop them all :)

Maybe put the in a second canned message if someone comes back saying they can't afford it etc?

But I want to push on this as hard as possible for 2 months. I think we've earned it! :)

**Comment by IsaacG** [comment]
> I'd personally drop them all :)
> 
> Maybe put the in a second canned message if someone comes back saying they can't afford it etc?
> 
> But I want to push on this as hard as possible for 2 months. I think we've earned it! :)

Mind taking a look at #110 ?

**Pull request closed without merging**
